### PR TITLE
[Master] Add tests for PP7 teaser list / PP6 teaser field visibility (Hjckrrh739)

### PR DESCRIPTION
**Pull request by mmafe**
**Note regarding base:** The PP7 teaser list has already been merged with hjckrrh's master so I'm opening a pull request to testing's master instead of next.

# Testing Dependencies
In order for these tests to work, your (hjckrrh) testing environment will need the following:
1. Master branch must be up-to-date with origin
   - Fetch the latest branch from origin / master which has the PP7 teaser available (see https://github.com/ccswbs/hjckrrh/pull/784 for merge details)
2. [Patch for Services Module 3.20](https://github.com/ccswbs/hjckrrh/pull/779) is necessary for this to run (branch = services-patch2)
   - If not merged onto master, create a separate testing branch off of master and merge services-patch2 onto that.

Once you have your branches ready:
1. Recreate your test site
2. Disable the UG Central Directory LDAP Server Configuration on your test site
   - Go to /admin/config/people/ldap/servers
   - Click "disable" beside the UG Central Directory configuration
3. Create a user called "sitemanager" with the Site Manager role enabled
4. Add the details for the "sitemanager" user to your environment.js file like so:

```
	creds:{
		admin:{
			username:"admin",
			password:"<insert password here>"
		},
		sitemanager:{
			username:"sitemanager",
			password:"<insert password here>"
		}
	},
```

# Tests to Run
Commands to run are:
- ```testcafe chrome tests/ug_profile/pp7.test.js```
- ```testcafe chrome tests/ug_profile/pp6.test.js```

# Expected Results

```
 UG Profile PP7 Teaser List View
 ✓ Profiles are shown randomly on PP7 teaser list view
 ✓ Selected fields show on Profiles PP7 teaser list view
 ✓ Title can be overridden on Profiles PP7 teaser list view
 ✓ More button text can be overridden on Profiles PP7 teaser list view
 ✓ Profiles PP7 teaser list view can be filtered by category term by Site Manager
 ✓ Profiles PP7 teaser list view can be filtered by keyword term by Site Manager
 6 passed

 UG Profile PP6 List View
 ✓ Selected fields show on Profiles PP6 listing view
 1 passed
```

**Note on duplicate functions:** There are a few functions that were duplicated in the pp6 and pp7 tests. I would prefer to have a single instance of each function in a more generic location. Some of the functions could work for tests across different content types (e.g. revertCustomPage, repeatClick), while others are very specific to profiles (e.g. generateProfiles). @nevantan Do you have a good suggestion for where I can put these functions (e.g. actions.js)?

### CODE REVIEW

**Comment by mmafe** [comment]
**Note:** After updating my local testing environment with ```npm update``` today, the login process for tests seems to have changed. 

Now, after logging in, the user does not seem to remain logged in for the duration of a function. In this case, after ```await Actions.Login(await t, Env.creds.admin.username, Env.creds.admin.password);``` the user is logged in, but does not appear to be logged in by the next line.

When testing, let me know if you are finding the same thing.

**Comment by nevantan** [comment]
I only had one error come up, and it was rare (< 1/10 times):
```
 ✖ Profiles are shown randomly on PP7 teaser list view

   1) - Error in test.before hook -
      The element that matches the specified selector is not visible.

      Browser: Chrome 60.0.3112 / Linux 0.0.0

         468 |		await t
         469 |			.navigateTo(Env.baseURL + '/node/' + generatedNodes[i].nodeID + '/edit')
         470 |			.setFilesToUpload(imageWidget, [
         471 |            '../../test_uploads/1.jpeg',
         472 |	        ])
       > 473 |	        .click(uploadImage)
         474 |	        .click(saveProfile);
         475 |	}
         476 |
         477 |	return generatedNodes;
         478 |}

         at <anonymous> (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:473:4)
         at step (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:553:460)
         at <anonymous> (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:553:630)

```
This looks like a wait-related error; that is, it is similar to errors we tend to work around with waits. I recommend @bdavey07 running these tests as my computer doesn't show these errors as often as they occur on other devices.

**Comment by nevantan** [comment]
Out of curiosity, I ran the tests on my phone. My current working theory is that my computer doesn't fail out in cases where @bdavey07's or @mmafe's computers do because pages load in faster. My phone is a lower powered device, so I thought it may fail out more consistently and it seems I was correct.

This is an error I didn't get on my computer at all, and I believe it would even go away on my phone if the waits were increased above the current 300ms:
```
✖ Profiles are shown randomly on PP7 teaser list view

   1) - Error in test.after hook -
      The element that matches the specified selector is not visible.

      Browser: Chrome Mobile 59.0.3071 / Android 7.1.1

         545 |		.navigateTo(Env.baseURL).wait(300)
         546 |		.setNativeDialogHandler(() => true)
         547 |		// open In-Place Editor
         548 |		.click(PeoplePage.auth.panelsCustomizeButton).wait(300)
         549 |		// remove PP7 View Pane
       > 550 |		.click(PeoplePage.auth.pp7.deleteButton).wait(300)
         551 |		// save In-Place Editor
         552 |		.click(PeoplePage.auth.panelsSaveButton).wait(300);
         553 |}
         554 |

         at <anonymous> (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:550:4)
         at step (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:553:460)
         at <anonymous> (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:553:700)
         at <anonymous> (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:553:361)
         at hidePP7 (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:553:50)
         at <anonymous> (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:560:226)
         at step (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:553:460)
         at <anonymous> (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:553:700)
         at <anonymous> (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:553:361)
         at test.before.after (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:560:327)

```

Unlike the computer-run test, the phone fails out on the Save button rather than the Upload button:
```
 ✖ Selected fields show on Profiles PP7 teaser list view

   1) - Error in test.before hook -
      The element that matches the specified selector is not visible.

      Browser: Chrome Mobile 59.0.3071 / Android 7.1.1

         469 |			.navigateTo(Env.baseURL + '/node/' + generatedNodes[i].nodeID + '/edit')
         470 |			.setFilesToUpload(imageWidget, [
         471 |            '../../test_uploads/1.jpeg',
         472 |	        ])
         473 |	        .click(uploadImage)
       > 474 |	        .click(saveProfile);
         475 |	}
         476 |
         477 |	return generatedNodes;
         478 |}
         479 |

         at <anonymous> (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:474:4)
         at step (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:553:460)
         at <anonymous> (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:553:630)
```

I think this last one can be ignored as it seems to be phone-specific and I don't think it's as important to support admin functions on mobile devices. Just adding it here for completeness:
```
 ✖ Profiles PP7 teaser list view can be filtered by category term by Site Manager

   1) - Error in test.before hook -
      A native alert dialog was invoked on page "http://127.0.0.1/iss739/node/157/edit", but no handler was set for it. Use
      the "setNativeDialogHandler" function to introduce a handler function for native dialogs.

      Browser: Chrome Mobile 59.0.3071 / Android 7.1.1

         469 |			.navigateTo(Env.baseURL + '/node/' + generatedNodes[i].nodeID + '/edit')
         470 |			.setFilesToUpload(imageWidget, [
         471 |            '../../test_uploads/1.jpeg',
         472 |	        ])
         473 |	        .click(uploadImage)
       > 474 |	        .click(saveProfile);
         475 |	}
         476 |
         477 |	return generatedNodes;
         478 |}
         479 |

         at <anonymous> (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:474:4)
         at step (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:553:460)
         at <anonymous> (/home/nevan/www/testing-hotfix/tests/ug_profile/pp7.test.js:553:630)
```

I believe most of these issues will be resolved by implementing the client-side load detection that is used in the breadcrumbs tests.

**Review by nevantan — CHANGES_REQUESTED** [review]
See comments above.

**Comment by mmafe** [comment]
# Recent notes
- To get around authentication issues (i.e. yak shaving), when navigating to homepage, I swapped ```Env.baseURL``` for ```Env.baseURL + '/front'```. Later on, it would be amazing to find out why this was causing issues on my machine because I suspect it's going to come up again, but for the time being '/front' seems to work.
- As recommended by @nevantan, swapped the waits for code similar to:
```
await t
   .eval(() => new Promise(resolve => setInterval(function() {
      if(jQuery('#panels-ipe-customize-page').length > 0) resolve();
   }, 500)));
```
- Once I started using the eval code, the dialog window that exists for removing the view pane no longer seem to have time enough to press the "OK" button. I ended up just throwing a .wait on the delete button to give the dialog window time. On second thought, it might be better just to revert the homepage - that way I don't have to remove a specific view pane at all.
- Moved the generic functions (generateProfiles, removeProfiles, generateTerms, removeTerms) into the Actions.js file

**Comment by mmafe** [comment]
Adding some new changes:
- adding another eval to pp6 test
- removing the hidePP6 and hidePP7 functions and swapped it out for a generic function that reverts a customPage (for the PP7, it's the homepage, for the PP6, it's the /people page)

**Comment by mmafe** [comment]
@nevantan @bdavey07 This branch (hjckrrh739-pp7) is available for testing now. You should be able to test against the master branch of hjckrrh.

**Review by nevantan — APPROVED** [review]

**Pull request merged**
